name: Release please workflow

on:
  push:
    branches:
      - master
    # paths:
    #   - "!README.md"
    #   - "!.github/**"
    #   - "*"

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  find-release-changes:
    name: Change finder for modules folders
    runs-on: ubuntu-latest
    outputs:
      module-paths: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: "Checkout for Push event (full history)"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed dirs
        id: get_changes
        uses: tj-actions/changed-files@v40
        with:
          dir_names: true
          files_ignore: |
            .github/workflows/**
            README.md
      
      - name: set matrix output
        id: set_matrix
        run: |
          tmp=(${{ steps.get_changes.outputs.all_changed_files }})
          X=($(for d in "${tmp[@]}"; do echo "${d}"; done | sort -u))
          json_array() {
            echo -n '['
            while [ $# -gt 0 ]; do
              x=${1//\\/\\\\}
              echo -n \"${x//\"/\\\"}\"
              [ $# -gt 1 ] && echo -n ', '
              shift
            done
            echo ']'
          }

          matrix=$(json_array "${X[@]}")
          echo "matrix=$matrix" >> $GITHUB_OUTPUT   

  release-pr:
    runs-on: ubuntu-latest
    needs: find-release-changes
    strategy:
      fail-fast: false
      matrix:
        module: ${{fromJson(needs.find-release-changes.outputs.module-paths)}}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          path: ${{ matrix.folder }}
          changelog-path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: terraform-module
          package-name: ${{ matrix.folder }}
          monorepo-tags: true
          command: release-pr

  release-please-release:
    runs-on: ubuntu-latest
    needs: find-release-changes
    strategy:
      fail-fast: false
      matrix:
        module: ${{fromJson(needs.find-release-changes.outputs.module-paths)}}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: tag-release
        with:
          path: ${{ matrix.folder }}
          changelog-path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: terraform-module
          monorepo-tags: true
          package-name: ${{ matrix.folder }}
          command: github-release      



 



  # validate-output:
  #   runs-on: ubuntu-latest
  #   needs: find-release-changes
  #   steps:
  #     - run: echo ${{fromJson(needs.find-release-changes.outputs.module-paths)}}

  # release-pr:
  #   runs-on: ubuntu-latest
  #   needs: find-release-changes
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       module: ${{fromJson(needs.find-release-changes.outputs.module-paths)}}
  #   steps:
  #     - uses: google-github-actions/release-please-action@v3
  #       id: release-please
  #       with:
  #         path: modules/${{ matrix.module }}
  #         changelog-path: CHANGELOG.md
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         release-type: terraform-module
  #         package-name: ${{ matrix.module }}
  #         monorepo-tags: true
  #         command: release-pr

  # release-please-release:
  #   runs-on: ubuntu-latest
  #   needs: find-release-changes
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       module: ${{fromJson(needs.find-release-changes.outputs.module-paths)}}
  #   steps:
  #     - uses: google-github-actions/release-please-action@v3
  #       id: tag-release
  #       with:
  #         path: modules/${{ matrix.module }}
  #         changelog-path: CHANGELOG.md
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         release-type: terraform-module
  #         monorepo-tags: true
  #         package-name: ${{ matrix.module }}
  #         command: github-release
